<a href="https://colab.research.google.com/github/atg2431-alpha/pytorch/blob/main/pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

**TENSORS**

In [ ]:
a = torch.empty(2,3)
a

tensor([[-1.3562e+15,  4.4658e-41, -1.3562e+15],
        [ 4.4658e-41, -1.3562e+15,  4.4658e-41]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
b = torch.tensor(([1,2,3],[4,5,6]))

In [ ]:
torch.full((2,3),5)

tensor([[5, 5, 5],
        [5, 5, 5]])

In [ ]:
b.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(b)

tensor([[136879946739072,       172509584, 136875376545984],
        [136875383034496, 136875361094400, 136875377391040]])

In [ ]:
torch.zeros_like(b)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(b)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(b,dtype=torch.float)
# torch.rand_like(b) won't work as it is in int but rand generates float objects

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
b.type

<function Tensor.type>

In [ ]:
b.dtype

torch.int64

**MATHS**

In [ ]:
print(b)
print(b+2)
print(b*2)
print(b/2)
print(b//2)
print(b**2)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[3, 4, 5],
        [6, 7, 8]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])
tensor([[0, 1, 1],
        [2, 2, 3]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [ ]:
torch.sum(b)

tensor(21)

In [ ]:
torch.sum(b, dim=0)
# 0 means column

tensor([5, 7, 9])

In [ ]:
b = b.to(dtype=torch.float)

In [ ]:
torch.std(b)

tensor(1.8708)

In [ ]:
torch.relu(b)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
b.relu_()
# b changes

tensor([[1., 2., 3.],
        [4., 5., 6.]])